import {
    Upload,
    Image as ImageIcon,
    Tag,
    FileText,
    X,
    Check,
    Link as LinkIcon,
    Code
} from 'lucide-react';
import { useLocation, useNavigate } from "react-router-dom";
import { useState, useRef, useEffect } from 'react';
import api, { API_URL } from "../lib/api";
import Swal from "sweetalert2";
import PageHeader from "../components/PageHeader";
import RichTextEditor from '../components/RichTextEditor';
import { List } from "lucide-react";


const CreatePage = () => {
    const editorRef = useRef(null);
    const schemaRef = useRef(null);
    const ogTagsRef = useRef(null);
    const navigate = useNavigate();
    const [isLoading, setIsLoading] = useState(false);
    const [fetchedImages, setFetchedImages] = useState({ main: null, gallery: [] });
    const [mongoId, setMongoId] = useState(null);

    // Form state
    const [formData, setFormData] = useState({
        postTitle: "",
        highlightedTitle: "",
        shortDescription: "",
        autoGeneratedTitle: "",
        permalink: "",
        serviceCategory: "",
        clients: "",
        altTag: "",
        location: "",
        height: "",
        width: "",
        depth: "",
        postDescription: "",
        postImage: null,
        imagePreview: null,
        postStatus: "inactive",

        // SEO Expansion
        metaTitle: "",
        metaKeywords: "",
        metaDescription: "",
        ogTitle: "",
        ogDescription: "",
        canonicalTag: "",
        schemaMarkup: "",
        openGraphTags: "",

        // Multiple images
        images: [
            { file: null, preview: null, alt: "" },
            { file: null, preview: null, alt: "" },
            { file: null, preview: null, alt: "" },
            { file: null, preview: null, alt: "" },
        ],
    });


    const serviceCategories = [
        'Retail Interiors',
        'Corporate Interiors',
        'Restaurant Interior',
        'Shop In Shops',
        'Retail Display Merchandising',
        'Acrylic Displays',
        'Gondolas',
        'Window Display',
        'Retail Kiosk',
        'Mobile Booth',
        'Modular Work Station',
        'MD Cabin',
        'Chairs',
        'Local Level Exhibition',
        'National Level Exhibition',
        'Modular Wardrobe',
        'Modular Kitchen',
        'Modular LCD Unit',
        'Dressing Table',
        'Interior Design Company',
        'Sofas',
        'Space Saving Furniture',
        'Exhibition & Events',
        'Signage',
        'MD Cabin',
        'Shop In Shops',
        'Window Display',
    ];

    const handleMultiImageChange = (index, file) => {
        if (!file) return;

        setFormData((prev) => {
            const updated = [...prev.images];
            updated[index] = {
                ...updated[index],
                file,
                preview: URL.createObjectURL(file),
            };
            return { ...prev, images: updated };
        });
    };

    const handleMultiImageAltChange = (index, value) => {
        setFormData((prev) => {
            const updated = [...prev.images];
            updated[index] = { ...updated[index], alt: value };
            return { ...prev, images: updated };
        });
    };

    const removeMultiImage = (index) => {
        setFormData((prev) => {
            const updated = [...prev.images];
            updated[index] = { file: null, preview: null, alt: "" };
            return { ...prev, images: updated };
        });
    };

    // Handle image upload
    const handleImageUpload = (e) => {
        const file = e.target.files[0];
        if (file) {
            setFormData(prev => ({
                ...prev,
                postImage: file,
                imagePreview: URL.createObjectURL(file)
            }));
        }
    };

    // Handle OG Image upload
    const handleOgImageUpload = (e) => {
        const file = e.target.files[0];
        if (file) {
            setFormData(prev => ({
                ...prev,
                ogImage: file,
                ogImagePreview: URL.createObjectURL(file)
            }));
        }
    };

    const location = useLocation();
    const pageId = location.state?.pageId || null;

    const handleInputChange = (e) => {
        const { name, value, type, checked } = e.target;
        setFormData(prev => ({
            ...prev,
            [name]: type === 'checkbox' ? checked : value
        }));
    };

    // Fetch data if editing
    useEffect(() => {
        if (pageId) {
            const fetchPage = async () => {
                setIsLoading(true);
                try {
                    const response = await api.get(`/api/custom-pages/slug/${pageId}`);
                    if (response.data.success) {
                        const page = response.data.data;
                        setMongoId(page._id);
                        setFormData({
                            postTitle: page.title || "",
                            highlightedTitle: page.highlightedTitle || "",
                            shortDescription: page.shortDescription || "",
                            permalink: page.permalink || "",
                            serviceCategory: page.serviceCategory || "",
                            location: page.location || "",
                            postDescription: page.postDescription || "",
                            postStatus: page.status || "inactive",
                            metaTitle: page.seo?.metaTitle || "",
                            metaKeywords: page.seo?.metaKeywords || page.seo?.metaKeyword || "",
                            metaDescription: page.seo?.metaDescription || "",
                            ogTitle: page.seo?.ogTitle || "",
                            ogDescription: page.seo?.ogDescription || "",
                            canonicalTag: page.seo?.canonicalTag || "",
                            schemaMarkup: page.seo?.schemaMarkup || "",
                            openGraphTags: page.seo?.openGraphTags || "",
                            imagePreview: page.mainImage?.url ? `${API_URL}${page.mainImage.url}` : null,
                            images: [
                                { file: null, preview: page.galleryImages?.[0]?.url ? `${API_URL}${page.galleryImages[0].url}` : null, alt: page.galleryImages?.[0]?.altTag || "" },
                                { file: null, preview: page.galleryImages?.[1]?.url ? `${API_URL}${page.galleryImages[1].url}` : null, alt: page.galleryImages?.[1]?.altTag || "" },
                                { file: null, preview: page.galleryImages?.[2]?.url ? `${API_URL}${page.galleryImages[2].url}` : null, alt: page.galleryImages?.[2]?.altTag || "" },
                                { file: null, preview: page.galleryImages?.[3]?.url ? `${API_URL}${page.galleryImages[3].url}` : null, alt: page.galleryImages?.[3]?.altTag || "" },
                            ],
                            altTag: page.mainImage?.altTag || "",
                            ogImagePreview: page.seo?.ogImage ? `${API_URL}${page.seo.ogImage}` : null,
                        });
                        setFetchedImages({
                            main: page.mainImage?.url,
                            gallery: page.galleryImages?.map(img => img.url) || []
                        });
                    }
                } catch (error) {
                    console.error("Error fetching page:", error);
                    Swal.fire("Error", "Failed to load page data", "error");
                } finally {
                    setIsLoading(false);
                }
            };
            fetchPage();
        }
    }, [pageId]);

    // Handle form submission
    const handleSubmit = async (e) => {
        e.preventDefault();
        setIsLoading(true);

        try {
            const data = new FormData();
            data.append("title", formData.postTitle);
            data.append("highlightedTitle", formData.highlightedTitle);
            data.append("shortDescription", formData.shortDescription);
            data.append("postDescription", formData.postDescription);
            data.append("permalink", formData.permalink);
            data.append("serviceCategory", formData.serviceCategory);
            data.append("location", formData.location);
            data.append("status", formData.postStatus);
            data.append("mainAlt", formData.altTag || "");

            // SEO
            data.append("metaTitle", formData.metaTitle);
            data.append("metaKeywords", formData.metaKeywords);
            data.append("metaDescription", formData.metaDescription);
            data.append("ogTitle", formData.ogTitle);
            data.append("ogDescription", formData.ogDescription);
            data.append("canonicalTag", formData.canonicalTag);
            data.append("schemaMarkup", formData.schemaMarkup);
            data.append("openGraphTags", formData.openGraphTags);

            // Images
            if (formData.postImage) {
                data.append("mainImage", formData.postImage);
            }

            if (formData.ogImage) {
                data.append("ogImage", formData.ogImage);
            }

            formData.images.forEach((img, index) => {
                if (img.file) {
                    data.append("galleryImages", img.file);
                }
                data.append("galleryAlts", img.alt || "");
            });

            let response;
            if (pageId && mongoId) {
                // We need the numeric/mongo ID for update
                response = await api.put(`/api/custom-pages/${mongoId}`, data);
            } else {
                response = await api.post("/api/custom-pages", data);
            }

            if (response.data.success) {
                Swal.fire("Success", `Page ${pageId ? 'updated' : 'created'} successfully!`, "success");
                navigate("/page-list");
            }
        } catch (error) {
            console.error("Error saving page:", error);
            Swal.fire("Error", error.response?.data?.message || "Failed to save page", "error");
        } finally {
            setIsLoading(false);
        }
    };

    // Format permalink
    const formatPermalink = (text) =>
        text
            .toLowerCase()
            .trim()
            .replace(/[^a-z0-9\s-]/g, "")
            .replace(/\s+/g, "-")
            .replace(/-+/g, "-");


    return (
        <div className="bg-white shadow-md p-6 mt-6 min-h-screen">
            {/* Header */}
            <PageHeader
                title="PAGE DOCUMENTATION"
                description="Create and manage your page content and portfolio projects"
                buttonText="Page List"
                buttonIcon={List}
                buttonPath="/page-list"
            />

            <form onSubmit={handleSubmit}>
                <div className="grid grid-cols-1 lg:grid-cols-4 gap-8">
                    {/* Left Column - Configuration & SEO (1/4) */}
                    <div className="lg:col-span-1 space-y-6">
                        {/* Page Status Card */}
                        <div className="bg-white border border-gray-200 p-6 shadow-sm rounded-lg">
                            <div className="flex items-center gap-3 mb-6">
                                <div className="p-2 bg-blue-50 rounded">
                                    <Tag className="w-5 h-5 text-blue-600" />
                                </div>
                                <h2 className="text-lg font-semibold text-gray-900 uppercase">Configuration</h2>
                            </div>

                            <div className="space-y-4">
                                <div>
                                    <label className="block text-[11px] font-semibold text-gray-500 mb-1.5 uppercase tracking-widest">Publication Status</label>
                                    <select
                                        value={formData.postStatus}
                                        onChange={(e) => setFormData({ ...formData, postStatus: e.target.value })}
                                        className={`w-full px-4 py-2.5 border-2 focus:outline-none transition-all rounded font-bold text-xs uppercase tracking-widest ${formData.postStatus === 'active'
                                            ? 'bg-green-50 border-green-200 text-green-700 focus:border-green-500'
                                            : 'bg-red-50 border-red-200 text-red-700 focus:border-red-500'
                                            }`}
                                    >
                                        <option value="active">● Published (Live)</option>
                                        <option value="inactive">○ Draft (Hidden)</option>
                                    </select>
                                </div>

                                <div>
                                    <label className="block text-[11px] font-semibold text-gray-500 mb-1.5 uppercase tracking-widest">Service Category *</label>
                                    <div className="relative">
                                        <select
                                            value={formData.serviceCategory}
                                            onChange={(e) => setFormData({ ...formData, serviceCategory: e.target.value })}
                                            className="w-full px-4 py-2.5 border border-gray-200 focus:outline-none focus:ring-1 focus:ring-[#134698] rounded bg-white text-sm font-medium appearance-none"
                                            required
                                            style={{ maxHeight: '200px' }}
                                        >
                                            <option value="">Select Category</option>
                                            {serviceCategories.map(cat => (
                                                <option key={cat} value={cat}>{cat}</option>
                                            ))}
                                        </select>
                                        <div className="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none text-gray-400">
                                            ▼
                                        </div>
                                    </div>
                                    <p className="text-[10px] text-gray-400 mt-1 italic">Click to select from available services.</p>
                                </div>

                                <div>
                                    <label className="block text-[11px] font-semibold text-gray-500 mb-1.5 uppercase tracking-widest">SEO Permalink *</label>
                                    <input
                                        type="text"
                                        value={formData.permalink}
                                        onChange={(e) => setFormData({ ...formData, permalink: formatPermalink(e.target.value) })}
                                        className="w-full px-4 py-2.5 border border-gray-200 focus:outline-none focus:ring-1 focus:ring-[#134698] rounded font-medium text-gray-800 text-xs"
                                        placeholder="seo-slug-here"
                                        required
                                    />
                                    <p className="text-[10px] text-gray-400 mt-1 italic">Automatically formatted for URL stability.</p>
                                </div>
                            </div>
                        </div>

                        {/* SEO Metadata Card */}
                        <div className="bg-white border border-gray-200 p-6 shadow-sm rounded-lg overflow-hidden">
                            <div className="flex items-center gap-3 mb-6">
                                <div className="p-2 bg-emerald-50 rounded">
                                    <FileText className="w-5 h-5 text-emerald-600" />
                                </div>
                                <h2 className="text-lg font-semibold text-gray-900 uppercase">SEO Metadata</h2>
                            </div>

                            <div className="space-y-4">
                                <div>
                                    <div className="flex justify-between items-center mb-1">
                                        <label className="block text-xs font-medium text-gray-700">
                                            Meta Title
                                        </label>
                                        <span className={`text-[10px] font-bold ${formData.metaTitle.length > 65 ? 'text-orange-500' : 'text-gray-400'}`}>
                                            {formData.metaTitle.length}/65
                                        </span>
                                    </div>
                                    <input
                                        type="text"
                                        name="metaTitle"
                                        value={formData.metaTitle}
                                        onChange={handleInputChange}
                                        placeholder="Enter meta title"
                                        className="w-full px-3 py-2 border-2 border-gray-300 focus:outline-none focus:border-[#134698] transition-colors text-xs shadow-sm"
                                    />
                                </div>
                                <div>
                                    <label className="block text-[11px] font-semibold text-gray-500 mb-1.5 uppercase tracking-widest">Meta Keywords</label>
                                    <input
                                        type="text"
                                        name="metaKeywords"
                                        value={formData.metaKeywords}
                                        onChange={handleInputChange}
                                        className="w-full px-4 py-2.5 border border-gray-200 focus:outline-none focus:ring-1 focus:ring-[#134698] rounded text-sm"
                                        placeholder="Keywords, separated by commas"
                                    />
                                </div>
                                <div>
                                    <div className="flex justify-between">
                                        <label className="block text-[11px] font-semibold text-gray-500 mb-1.5 uppercase tracking-widest">Meta Description</label>
                                        <span className={`text-[10px] font-bold ${formData.metaDescription.length > 155 ? 'text-red-500' : 'text-gray-400'}`}>
                                            {formData.metaDescription.length}/155
                                        </span>
                                    </div>
                                    <textarea
                                        name="metaDescription"
                                        value={formData.metaDescription}
                                        onChange={handleInputChange}
                                        rows={3}
                                        maxLength={155}
                                        className="w-full px-4 py-2 border border-gray-300 focus:outline-none focus:ring-1 focus:ring-[#134698] rounded font-medium text-sm resize-none"
                                        placeholder="Brief summary for search results..."
                                    />
                                </div>

                                {/* OG Tags */}
                                <div className="pt-4 border-t border-gray-100">
                                    <h3 className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-3">Open Graph (Social Sharing)</h3>
                                    <div className="space-y-3">
                                        <div>
                                            <input
                                                type="text"
                                                value={formData.ogTitle}
                                                onChange={(e) => setFormData({ ...formData, ogTitle: e.target.value })}
                                                className="w-full px-3 py-2 border border-gray-200 focus:outline-none focus:ring-1 focus:ring-[#134698] rounded text-[11px]"
                                                placeholder="OG Title (Social Title)"
                                            />
                                        </div>
                                        <div>
                                            <textarea
                                                value={formData.ogDescription}
                                                onChange={(e) => setFormData({ ...formData, ogDescription: e.target.value })}
                                                rows={2}
                                                className="w-full px-3 py-2 border border-gray-200 focus:outline-none focus:ring-1 focus:ring-[#134698] rounded text-[11px] resize-none"
                                                placeholder="OG Description (Social Summary)"
                                            />
                                        </div>
                                        <div>
                                            <h3 className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-2 flex items-center gap-1">
                                                <Code className="w-3 h-3" /> Additional OG Tags (Paste Tags Directly)
                                            </h3>
                                            <RichTextEditor
                                                value={formData.openGraphTags}
                                                onChange={(val) => setFormData(prev => ({ ...prev, openGraphTags: val }))}
                                                placeholder='<meta property="..." content="..." />'
                                                minHeight="100px"
                                                isCodeEditor={true}
                                            />
                                        </div>
                                        <div>
                                            <label className="block text-[9px] font-bold text-gray-400 uppercase mb-1">OG Image</label>
                                            <div className="border border-dashed border-gray-300 rounded p-2 text-center relative hover:bg-gray-50 transition-colors">
                                                <input
                                                    type="file"
                                                    onChange={handleOgImageUpload}
                                                    className="absolute inset-0 opacity-0 cursor-pointer z-10"
                                                    accept="image/*"
                                                />
                                                {formData.ogImagePreview ? (
                                                    <img src={formData.ogImagePreview} alt="OG Preview" className="h-16 w-full object-cover rounded" />
                                                ) : (
                                                    <div className="py-2">
                                                        <ImageIcon className="w-4 h-4 text-gray-300 mx-auto" />
                                                        <span className="text-[8px] text-gray-400 block mt-1 uppercase font-bold tracking-tighter">Upload OG Image</span>
                                                    </div>
                                                )}
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                {/* Canonical Tag */}
                                <div className="pt-4 border-t border-gray-100">
                                    <h3 className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-2 flex items-center gap-1">
                                        <LinkIcon className="w-3 h-3" /> Canonical Tag
                                    </h3>
                                    <input
                                        type="text"
                                        value={formData.canonicalTag}
                                        onChange={(e) => setFormData({ ...formData, canonicalTag: e.target.value })}
                                        placeholder="Enter canonical URL"
                                        className="w-full px-3 py-1.5 border border-gray-200 focus:outline-none focus:ring-1 focus:ring-[#134698] rounded text-[10px] font-medium"
                                    />
                                </div>

                                {/* Schema Markup */}
                                <div className="pt-4 border-t border-gray-100">
                                    <h3 className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-2 flex items-center gap-1">
                                        <Code className="w-3 h-3" /> Schema Markup (JSON-LD)
                                    </h3>
                                    <RichTextEditor
                                        value={formData.schemaMarkup}
                                        onChange={(val) => setFormData(prev => ({ ...prev, schemaMarkup: val }))}
                                        placeholder='{"@context": "https://schema.org", ...}'
                                        minHeight="150px"
                                        isCodeEditor={true}
                                    />
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Right Column - Main Content (3/4) */}
                    <div className="lg:col-span-3 space-y-6">
                        {/* Main Form Fields */}
                        <div className="bg-white border border-gray-200 shadow-md rounded-lg overflow-hidden">
                            <div className="px-6 py-4 border-b border-gray-100 flex justify-between items-center bg-gray-50/50">
                                <h3 className="text-lg font-semibold text-[#1e3a8a] uppercase tracking-tight">
                                    {pageId ? 'Update Existing Page' : 'Page Primary Content'}
                                </h3>
                            </div>

                            <div className="p-6">
                                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                    {/* Titles */}
                                    <div className="space-y-5">
                                        <div>
                                            <label className="block text-[11px] font-semibold text-gray-500 mb-1.5 uppercase tracking-widest">Page Main Title (H1 for SEO) *</label>
                                            <input
                                                type="text"
                                                value={formData.postTitle}
                                                onChange={(e) => setFormData({ ...formData, postTitle: e.target.value })}
                                                className="w-full px-4 py-3 border border-gray-200 shadow-lg focus:outline-none focus:ring-1 focus:ring-[#134698] rounded font-medium text-gray-800"
                                                placeholder="Enter project name (H1)..."
                                                required
                                            />
                                        </div>
                                        <div>
                                            <label className="block text-[11px] font-semibold text-gray-500 mb-1.5 uppercase tracking-widest">Highlighted Heading</label>
                                            <input
                                                type="text"
                                                value={formData.highlightedTitle}
                                                onChange={(e) => setFormData({ ...formData, highlightedTitle: e.target.value })}
                                                className="w-full px-4 py-3 border border-gray-200 shadow-lg focus:outline-none focus:ring-1 focus:ring-[#134698] rounded font-medium text-gray-800"
                                                placeholder="Enter highlight title..."
                                            />
                                        </div>
                                    </div>

                                    {/* Meta info */}
                                    <div className="space-y-5">
                                        <div>
                                            <label className="block text-[11px] font-semibold text-gray-500 mb-1.5 uppercase tracking-widest">Short Summary *</label>
                                            <input
                                                type="text"
                                                value={formData.shortDescription}
                                                onChange={(e) => setFormData({ ...formData, shortDescription: e.target.value })}
                                                className="w-full px-4 py-3 border border-gray-200 shadow-lg focus:outline-none focus:ring-1 focus:ring-[#134698] rounded font-medium text-gray-800"
                                                placeholder="One-line description..."
                                                required
                                            />
                                        </div>
                                        <div className="grid grid-cols-2 gap-4">
                                            <div>
                                                <label className="block text-[11px] font-semibold text-gray-500 mb-1.5 uppercase tracking-widest">Client Name</label>
                                                <input
                                                    type="text"
                                                    value={formData.clients}
                                                    onChange={(e) => setFormData({ ...formData, clients: e.target.value })}
                                                    className="w-full px-4 py-3 border border-gray-200 shadow-lg focus:outline-none focus:ring-1 focus:ring-[#134698] rounded font-medium text-gray-800"
                                                    placeholder="Client detail..."
                                                />
                                            </div>
                                            <div>
                                                <label className="block text-[11px] font-semibold text-gray-500 mb-1.5 uppercase tracking-widest">Project Location</label>
                                                <input
                                                    type="text"
                                                    value={formData.location}
                                                    onChange={(e) => setFormData({ ...formData, location: e.target.value })}
                                                    className="w-full px-4 py-3 border border-gray-200 shadow-lg focus:outline-none focus:ring-1 focus:ring-[#134698] rounded font-medium text-gray-800"
                                                    placeholder="e.g. Noida, Sector 62"
                                                />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            {/* Rich Text Editor */}
                            <div className="mt-8 space-y-2">
                                <label className="block text-[11px] font-semibold text-gray-500 uppercase tracking-widest flex items-center gap-2">
                                    Detailed Description *
                                </label>
                                <div className="bg-white border-2 border-gray-200 shadow-lg p-8 rounded-lg text-left">
                                    <h2 className="text-xl font-bold mb-6 text-gray-900 uppercase">Detailed Description</h2>
                                    <RichTextEditor
                                        value={formData.postDescription}
                                        onChange={(val) => setFormData(prev => ({ ...prev, postDescription: val }))}
                                        placeholder="Start typing page content..."
                                        minHeight="400px"
                                    />
                                </div>
                            </div>

                            {/* Featured Image Upload */}
                            <div className="mt-8">
                                <label className="block text-[11px] font-semibold text-gray-500 mb-2 uppercase tracking-widest">Main Display Image *</label>
                                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                                    <div className="md:col-span-1">
                                        <div className="border border-dashed border-gray-300 p-4 text-center relative group min-h-[200px] flex items-center justify-center bg-gray-50/30 rounded-lg hover:border-[#1e3a8a] transition-colors overflow-hidden">
                                            <input
                                                type="file"
                                                onChange={handleImageUpload}
                                                className="absolute inset-0 opacity-0 cursor-pointer z-20"
                                                accept="image/*"
                                            />
                                            {formData.imagePreview ? (
                                                <div className="relative w-full h-full">
                                                    <img src={formData.imagePreview} alt="Preview" className="w-full h-40 object-cover rounded shadow-sm" />
                                                    <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center rounded z-10">
                                                        <span className="text-white text-xs font-bold uppercase tracking-wider">Replace Image</span>
                                                    </div>
                                                </div>
                                            ) : (
                                                <div className="flex flex-col items-center py-4">
                                                    <Upload className="w-10 h-10 text-gray-300 mb-2" />
                                                    <p className="text-[10px] font-semibold text-gray-400 uppercase tracking-widest">Upload Main Banner</p>
                                                </div>
                                            )}
                                        </div>
                                    </div>
                                    <div className="md:col-span-2 bg-blue-50/50 p-6 rounded-lg border border-blue-100 flex flex-col justify-center">
                                        <p className="text-[#134698] text-sm font-bold uppercase mb-2">Image Requirements</p>
                                        <ul className="text-[11px] text-gray-600 space-y-1.5 uppercase tracking-wide">
                                            <li className="flex items-center gap-2"><Check className="w-3 h-3 text-green-600" /> Resolution: 1920x1080</li>
                                            <li className="flex items-center gap-2"><Check className="w-3 h-3 text-green-600" /> Format: JPG, PNG, WEBP Only</li>
                                            <li className="flex items-center gap-2"><Check className="w-3 h-3 text-green-600" /> Max Size: 10MB per image</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>

                            {/* Main Image Alt Text */}
                            <div className="mt-4">
                                <label className="block text-[11px] font-semibold text-gray-500 mb-1.5 uppercase tracking-widest">Main Image Alt Text (SEO)</label>
                                <input
                                    type="text"
                                    value={formData.altTag}
                                    onChange={(e) => setFormData({ ...formData, altTag: e.target.value })}
                                    className="w-full px-4 py-2.5 border border-gray-200 focus:outline-none focus:ring-1 focus:ring-[#134698] rounded font-medium text-gray-800 text-sm"
                                    placeholder="Describe the main image for SEO..."
                                />
                            </div>


                            {/* Gallery Section */}
                            <div className="mt-10 pt-10 border-t border-gray-100">
                                <h3 className="text-sm font-bold text-gray-800 uppercase tracking-wider mb-6">Project Gallery (Upload up to 4 Additional Images)</h3>
                                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
                                    {formData.images.map((img, index) => (
                                        <div key={index} className="space-y-3">
                                            <div className="border border-dashed border-gray-300 rounded-lg p-2 bg-gray-50 relative group transition-all hover:bg-white hover:border-[#1e3a8a]">
                                                <div className="h-28 w-full rounded flex items-center justify-center overflow-hidden bg-white">
                                                    {img.preview ? (
                                                        <div className="relative w-full h-full">
                                                            <img src={img.preview} alt={`Gallery ${index}`} className="w-full h-full object-cover" />
                                                            <button
                                                                type="button"
                                                                onClick={() => removeMultiImage(index)}
                                                                className="absolute top-1 right-1 bg-white/90 text-red-600 p-1 rounded shadow hover:bg-red-50"
                                                            >
                                                                <X className="w-3 h-3" />
                                                            </button>
                                                        </div>
                                                    ) : (
                                                        <div className="relative w-full h-full flex flex-col items-center justify-center">
                                                            <ImageIcon className="w-6 h-6 text-gray-300 mb-1" />
                                                            <span className="text-[9px] font-bold text-gray-400 uppercase">Select Image {index + 1}</span>
                                                            <input
                                                                type="file"
                                                                accept="image/*"
                                                                className="absolute inset-0 opacity-0 cursor-pointer"
                                                                onChange={(e) => handleMultiImageChange(index, e.target.files[0])}
                                                            />
                                                        </div>
                                                    )}
                                                </div>
                                            </div>
                                            <input
                                                type="text"
                                                value={img.alt}
                                                onChange={(e) => handleMultiImageAltChange(index, e.target.value)}
                                                placeholder="SEO Alt Tag"
                                                className="w-full px-3 py-1.5 border border-gray-200 focus:outline-none focus:ring-1 focus:ring-[#134698] rounded text-[10px] font-medium placeholder:italic shadow-sm"
                                            />
                                        </div>
                                    ))}
                                </div>
                            </div>

                            {/* Submit Button */}
                            <div className="mt-12 flex justify-end">
                                <button
                                    type="submit"
                                    className="px-12 py-3.5 bg-[#1e3a8a] text-white font-bold rounded shadow-lg hover:bg-[#162a63] hover:shadow-xl transition-all flex items-center gap-3 uppercase text-sm tracking-widest"
                                >
                                    <Check className="w-5 h-5" />
                                    {pageId ? "Update Page Entry" : "Publish to Portfolio"}
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </form >

        </div >
    );
};

export default CreatePage;